version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    container_name: example-service-app
    volumes:
      - ${PWD}:/app
    ports:
      - ${DOCKER_APP_PUBLISHING_PORT}:${APP_PORT}
    depends_on:
      - postgres
    networks:
      - meetings-app-network
    env_file:
      - .env

  postgres:
    image: postgres:14.3-alpine
    container_name: example-service-db
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    networks:
      - meetings-app-network
    ports:
      - ${DOCKER_DB_PUBLISHING_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data

networks:
  meetings-app-network:
    external: true
